Repository iov-one/ponferrada, pull requests merged in 2019-05, with the labels that each got.

#115 Feature - Adding Signup route E2E tests
  packages/sanes-chrome-extension/package.json
  packages/sanes-chrome-extension/src/routes/signup/components/NewAccountForm.tsx
  packages/sanes-chrome-extension/src/routes/signup/index.e2e.spec.ts
  packages/sanes-chrome-extension/src/routes/signup/test/fillSignupForm.ts
  packages/sanes-chrome-extension/src/routes/signup/test/travelToSignup.ts
  packages/sanes-chrome-extension/src/routes/welcome/index.e2e.spec.tsx
  packages/sanes-chrome-extension/src/utils/test/e2e.ts
  packages/sanes-chrome-extension/src/utils/test/reactElemFinder.ts
Labels: Feature, WIP

#122 Feature - Restore account logic
  packages/sanes-chrome-extension/src/context/PersonaProvider.tsx
  packages/sanes-chrome-extension/src/routes/restore-account/index.dom.spec.ts
  packages/sanes-chrome-extension/src/routes/restore-account/index.e2e.spec.ts
  packages/sanes-chrome-extension/src/routes/restore-account/index.tsx
  packages/sanes-chrome-extension/src/routes/restore-account/test/fillRecoveryPhrase.ts
  packages/sanes-chrome-extension/src/routes/restore-account/test/travelToRestoreAccount.ts
  packages/sanes-chrome-extension/src/routes/signup/index.dom.spec.ts
  packages/sanes-chrome-extension/src/utils/test/e2e.ts
Labels: Feature

#129 Feature - Share identity main view
  packages/sanes-chrome-extension/src/routes/share-identity/components/index.tsx
  packages/sanes-chrome-extension/src/routes/share-identity/index.stories.tsx
  packages/sanes-chrome-extension/src/routes/share-identity/index.tsx
  packages/valdueza-storybook/src/__snapshots__/Storyshots.test.js.snap
Labels: Feature, Frontend 😊

#149 Fix - Chrome Extension Storybook Routes
  packages/sanes-chrome-extension/src/routes/account/index.stories.tsx
  packages/sanes-chrome-extension/src/routes/login/index.stories.tsx
  packages/sanes-chrome-extension/src/routes/recovery-phrase/index.stories.tsx
  packages/sanes-chrome-extension/src/routes/restore-account/index.stories.tsx
  packages/sanes-chrome-extension/src/routes/share-identity/index.stories.tsx
  packages/sanes-chrome-extension/src/routes/signup/index.stories.tsx
  packages/sanes-chrome-extension/src/routes/welcome/index.stories.tsx
  packages/valdueza-storybook/src/__snapshots__/Storyshots.test.js.snap
Labels: Fix

#130 Feature #16 - Share identity accept view
  packages/sanes-chrome-extension/src/routes/share-identity/components/AcceptRequest.tsx
  packages/sanes-chrome-extension/src/routes/share-identity/components/ShowRequest.tsx
  packages/sanes-chrome-extension/src/routes/share-identity/index.stories.tsx
  packages/sanes-chrome-extension/src/routes/share-identity/index.tsx
  packages/valdueza-storybook/src/__snapshots__/Storyshots.test.js.snap
Labels: Feature, Frontend 😊

#138 Feature #16 - Share identity reject view
  packages/bierzo-wallet/src/routes/payment/index.stories.tsx
  packages/bierzo-wallet/src/routes/welcome/index.stories.tsx
  packages/bierzo-wallet/src/utils/storybook/index.tsx
  packages/medulas-react-components/package.json
  packages/medulas-react-components/src/components/forms/CheckboxField/index.stories.tsx
  packages/medulas-react-components/src/components/forms/CheckboxField/index.tsx
  packages/medulas-react-components/src/components/forms/Form/index.stories.tsx
  packages/medulas-react-components/src/components/forms/TextFieldForm/index.stories.tsx
  packages/sanes-chrome-extension/src/routes/account/index.stories.tsx
  packages/sanes-chrome-extension/src/routes/login/index.stories.tsx
  packages/sanes-chrome-extension/src/routes/recovery-phrase/index.stories.tsx
  packages/sanes-chrome-extension/src/routes/restore-account/index.stories.tsx
  packages/sanes-chrome-extension/src/routes/share-identity/components/RejectRequest.tsx
  packages/sanes-chrome-extension/src/routes/share-identity/components/ShowRequest.tsx
  packages/sanes-chrome-extension/src/routes/share-identity/index.stories.tsx
  packages/sanes-chrome-extension/src/routes/share-identity/index.tsx
  packages/sanes-chrome-extension/src/routes/signup/index.stories.tsx
  packages/sanes-chrome-extension/src/routes/welcome/index.stories.tsx
  packages/sanes-chrome-extension/src/utils/storybook/index.tsx
  packages/valdueza-storybook/src/__snapshots__/Storyshots.test.js.snap
  yarn.lock
Labels: Feature, Frontend 😊

#141 Feature – Navigate to show account when Persona exists
  packages/sanes-chrome-extension/src/extension/bsMessageHandler/externalHandler.ts
  packages/sanes-chrome-extension/src/extension/bsMessageHandler/internalHandler.ts
  packages/sanes-chrome-extension/src/extension/messages.ts
  packages/sanes-chrome-extension/src/routes/welcome/index.tsx
Labels: merge when green

#157 Feature – Show transactions in UI and create sendAndPost example
  packages/bierzo-wallet/src/communication/identities/index.ts
  packages/bierzo-wallet/src/communication/signAndPost/index.ts
  packages/bierzo-wallet/src/routes/welcome/index.tsx
  packages/sanes-chrome-extension/src/context/PersonaProvider.tsx
  packages/sanes-chrome-extension/src/extension/bsMessageHandler/internalHandler.ts
  packages/sanes-chrome-extension/src/extension/messages.ts
  packages/sanes-chrome-extension/src/logic/persona/persona.ts
  packages/sanes-chrome-extension/src/logic/persona/persona.unit.spec.ts
  packages/valdueza-storybook/src/__snapshots__/Storyshots.test.js.snap
Labels: merge when green

#159 Fix - Set default viewport of the Wallet to the responsive value
  packages/bierzo-wallet/src/routes/payment/index.stories.tsx
  packages/bierzo-wallet/src/routes/welcome/index.stories.tsx
Labels: Fix

#150 Feature #16 - Share identity DOM tests
  packages/sanes-chrome-extension/src/routes/account/index.stories.tsx
  packages/sanes-chrome-extension/src/routes/index.tsx
  packages/sanes-chrome-extension/src/routes/paths.ts
  packages/sanes-chrome-extension/src/routes/share-identity/components/AcceptRequest.tsx
  packages/sanes-chrome-extension/src/routes/share-identity/components/RejectRequest.tsx
  packages/sanes-chrome-extension/src/routes/share-identity/components/ShowRequest.tsx
  packages/sanes-chrome-extension/src/routes/share-identity/index.dom.spec.ts
  packages/sanes-chrome-extension/src/routes/share-identity/index.stories.tsx
  packages/sanes-chrome-extension/src/routes/share-identity/index.tsx
  packages/sanes-chrome-extension/src/routes/share-identity/test/operateShareIdentity.ts
  packages/sanes-chrome-extension/src/routes/share-identity/test/travelToShareIdentity.ts
  packages/valdueza-storybook/src/__snapshots__/Storyshots.test.js.snap
Labels: Feature

#161 Feature #88 Hamburger menu in account status
  packages/bierzo-wallet/src/theme/globalStyles.ts
  packages/medulas-react-components/src/components/Drawer/index.stories.tsx
  packages/medulas-react-components/src/components/Drawer/index.tsx
  packages/medulas-react-components/src/theme/utils/mui.ts
  packages/sanes-chrome-extension/src/routes/account/index.tsx
  packages/valdueza-storybook/src/__snapshots__/Storyshots.test.js.snap
Labels: merge when green

#170 Feature #31 - Transaction Request Views
  packages/sanes-chrome-extension/src/routes/paths.ts
  packages/sanes-chrome-extension/src/routes/tx-request/components/RejectRequest.tsx
  packages/sanes-chrome-extension/src/routes/tx-request/components/ShowRequest.tsx
  packages/sanes-chrome-extension/src/routes/tx-request/index.stories.tsx
  packages/sanes-chrome-extension/src/routes/tx-request/index.tsx
  packages/valdueza-storybook/src/__snapshots__/Storyshots.test.js.snap
Labels: Feature, Frontend 😊, merge when green

#185 Feature #31 - Transaction Request Tests
  packages/medulas-react-components/src/components/Button/Back.tsx
  packages/sanes-chrome-extension/src/routes/index.tsx
  packages/sanes-chrome-extension/src/routes/tx-request/index.dom.spec.ts
  packages/sanes-chrome-extension/src/routes/tx-request/test/operateTXRequest.ts
  packages/sanes-chrome-extension/src/routes/tx-request/test/travelToTXRequest.ts
  packages/valdueza-storybook/src/__snapshots__/Storyshots.test.js.snap
Labels: Feature, merge when green

#196 Feature #165 - DOM tests for recovery-phrase
  packages/medulas-react-components/src/components/Drawer/index.tsx
  packages/sanes-chrome-extension/src/routes/account/test/travelToAccount.ts
  packages/sanes-chrome-extension/src/routes/recovery-phrase/components/ShowRecoveryPhrase.tsx
  packages/sanes-chrome-extension/src/routes/recovery-phrase/index.dom.spec.ts
  packages/sanes-chrome-extension/src/routes/recovery-phrase/index.tsx
  packages/sanes-chrome-extension/src/routes/recovery-phrase/test/travelToRecoveryPhrase.ts
  packages/sanes-chrome-extension/src/routes/signup/index.dom.spec.ts
  packages/sanes-chrome-extension/src/routes/signup/test/travelToSignup.ts
  packages/valdueza-storybook/src/__snapshots__/Storyshots.test.js.snap
Labels: Feature

#208 Feature #203 - Unit tests for SenderWhitelist
  packages/sanes-chrome-extension/src/extension/background/actions/createPersona/requestSenderWhitelist/index.ts
  packages/sanes-chrome-extension/src/extension/background/actions/createPersona/requestSenderWhitelist/index.unit.spec.ts
Labels: Feature

#209 Feature #169 - Remove pending transactions
  packages/sanes-chrome-extension/src/routes/account/index.tsx
  packages/valdueza-storybook/src/__snapshots__/Storyshots.test.js.snap
Labels: Feature

#216 Feature – Use constant chain IDs bns-local-devnet, bcp-local-devnet
  scripts/bcpd/bcpd_init.sh
  scripts/bnsd/bnsd_init.sh
Labels: merge when green

#215 Fix - Simplifies access to blocked list in SenderWhitelist unit test
  packages/sanes-chrome-extension/src/extension/background/actions/createPersona/requestSenderWhitelist/index.unit.spec.ts
Labels: Fix

#205 Feature #201 - Show real data tx-request and share-identity requests
  packages/sanes-chrome-extension/src/routes/requests/components/RequestList.tsx
  packages/sanes-chrome-extension/src/routes/requests/index.tsx
  packages/sanes-chrome-extension/src/routes/share-identity/components/RejectRequest.tsx
  packages/sanes-chrome-extension/src/routes/share-identity/components/ShowRequest.tsx
  packages/sanes-chrome-extension/src/routes/share-identity/index.stories.tsx
  packages/sanes-chrome-extension/src/routes/share-identity/index.tsx
  packages/sanes-chrome-extension/src/routes/tx-request/components/RejectRequest.tsx
  packages/sanes-chrome-extension/src/routes/tx-request/components/ShowRequest.tsx
  packages/sanes-chrome-extension/src/routes/tx-request/index.stories.tsx
  packages/sanes-chrome-extension/src/routes/tx-request/index.tsx
  packages/valdueza-storybook/src/__snapshots__/Storyshots.test.js.snap
Labels: Feature, Frontend 😊

#214 Feature #200 - Unit tests for RequestHandler
  packages/sanes-chrome-extension/src/extension/background/actions/createPersona/requestHandler/index.ts
  packages/sanes-chrome-extension/src/extension/background/actions/createPersona/requestHandler/index.unit.spec.ts
Labels: Feature

#225 Hotfix - Separating integration tests
  packages/bierzo-wallet/package.json
  packages/bierzo-wallet/src/routes/welcome/index.e2e.spec.ts
  packages/bierzo-wallet/src/utils/test/e2e.ts
  yarn.lock
Labels: merge when green

#226 Feature #111 - DOM tests for Account Status view
  packages/sanes-chrome-extension/src/routes/account/index.dom.spec.ts
  packages/sanes-chrome-extension/src/routes/account/test/travelToAccount.ts
Labels: Feature

#229 Fix #223 - Update extension badge after brower restart
  packages/sanes-chrome-extension/src/extension/backgroundscript.ts
Labels: Fix

#222 Feature #193 - DOM tests for Requests view
  packages/sanes-chrome-extension/src/routes/requests/index.dom.spec.ts
  packages/sanes-chrome-extension/src/routes/requests/test/travelToRequests.ts
  packages/sanes-chrome-extension/src/store/reducers/index.ts
Labels: Feature, bug, merge when green

#160 Fix - Avoid exceeding maximum update depth
  packages/bierzo-wallet/src/routes/payment/components/CurrencyToSend/index.tsx
  packages/bierzo-wallet/src/routes/payment/components/ReceiverAddress/index.tsx
  packages/bierzo-wallet/src/routes/payment/components/TextNote/index.tsx
Labels: Fix, WIP, bug

#238 Feature #212 - Improve Bierzo Wallet Usability with Toast messages
  packages/bierzo-wallet/src/routes/welcome/index.tsx
Labels: Feature

#242 Feature #217 - Password fields for Restore Account view
  packages/medulas-react-components/src/utils/forms/validators/index.tsx
  packages/sanes-chrome-extension/src/routes/account/index.e2e.spec.ts
  packages/sanes-chrome-extension/src/routes/restore-account/components/SetMnemonicForm.tsx
  packages/sanes-chrome-extension/src/routes/restore-account/components/SetPasswordForm.tsx
  packages/sanes-chrome-extension/src/routes/restore-account/index.dom.spec.ts
  packages/sanes-chrome-extension/src/routes/restore-account/index.e2e.spec.ts
  packages/sanes-chrome-extension/src/routes/restore-account/index.stories.tsx
  packages/sanes-chrome-extension/src/routes/restore-account/index.tsx
  packages/sanes-chrome-extension/src/routes/restore-account/test/fillRecoveryPhrase.ts
  packages/valdueza-storybook/src/__snapshots__/Storyshots.test.js.snap
Labels: Feature
